#! /bin/sh
wget -O commons-io-2.6.jar https://repo1.maven.org/maven2/commons-io/commons-io/2.6/commons-io-2.6.jar

wget -O commons-lang3-3.10.jar https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.10/commons-lang3-3.10.jar
 
wget -O commons-text-1.8.jar https://repo1.maven.org/maven2/org/apache/commons/commons-text/1.8/commons-text-1.8.jar

wget -O juniversalchardet-1.0.3.jar https://repo1.maven.org/maven2/com/googlecode/juniversalchardet/juniversalchardet/1.0.3/juniversalchardet-1.0.3.jar
   